import { Match, NewsItem } from "./types";

export const INITIAL_NEWS: NewsItem[] = [
  {
    id: "n1",
    title: "تحليل الذكاء الاصطناعي: كيف غيّر جوارديولا فلسفة الكتل الدفاعية في البريميرليغ؟",
    summary: "تحليل تكتيكي من عمق خوارزمياتنا يستعرض التموضع الهجين للأجنحة وتأثيرها على تفكيك دفاعات الخصوم.",
    content: "نجح بيب جوارديولا في فرض أسلوب تكتيكي جديد يعتمد على الأجنحة الوهمية واللاعب رقم 5 الهجين، مما تسبب في إرباك تام للمنظومات الدفاعية الكلاسيكية. تشير الإحصائيات الفورية إلى أن سرعة استعادة الكرة تقلصت إلى 4.2 ثوانٍ فقط، مما يجعل الخصم تحت طائلة الضغط المستمر. يتوقع نموذج الذكاء الاصطناعي الخاص بنا زيادة مرتقبة في نسبة الأهداف من ألعاب متحركة بنسبة 11% للفرق التي تعتمد هذا الملخص الهجين في المواسم المقبلة.",
    teamTag: "الدوري الإنجليزي",
    imageUrl: "https://images.unsplash.com/photo-1518063319789-7217e6706b04?auto=format&fit=crop&w=500&q=80",
    date: "2026-06-13",
    aiGenerated: true
  },
  {
    id: "n2",
    title: "الهلال يستعرض عضلاته مجدداً: قراءة تحليلية في جودة صناعة الألعاب الفورية",
    summary: "قراءة في الأرقام والمؤشرات الرقمية التي تبرهن تفوق ترسانة الزعيم أمام المنافسين في خط الظهر.",
    content: "يستمر نادي الهلال في تقديم وجبة تكتيكية دسمة لجماهيره. أداء خط الوسط المذهل والقدرة العالية على الفوز بالثنائيات بنسبة 64% عززت من قدرة الفريق على تسيير ريتم المباريات بنجاح مذهل. يرى محلل الذكاء الاصطناعي لدينا أن هذا التنظيم الصارم هو المفتاح لحملة الدفاع عن اللقب الآسيوي والمحلي على حد سواء.",
    teamTag: "دوري روشن",
    imageUrl: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&w=500&q=80",
    date: "2026-06-13",
    aiGenerated: true
  },
  {
    id: "n3",
    title: "مستقبل التوقعات الكروية: كيف تحدد الخوارزميات الفائزين بالدوريات الكبرى؟",
    summary: "استعراض لعلماء البيانات حول فاعلية نماذج الذكاء الاصطناعي الرياضية مقارنة بالطرق التقليدية.",
    content: "تعتمد خوارزميات الذكاء الاصطناعي الحالية على تتبع أكثر من 40,000 إحداثي حركي لكل لاعب خلال الـ 90 دقيقة. هذا النموذج الرياضي يحسب بدقة متزايدة فرص الأهداف المتوقعة (xG) ونسب تفاعل ثنائيات الدفاع مما يوفر للمستثمرين في الإعلانات والقنوات الإعلامية تحليلاً في غاية الدقة والسرعة.",
    teamTag: "تقنية رياضية",
    imageUrl: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=500&q=80",
    date: "2026-06-12",
    aiGenerated: true
  }
];

export const INITIAL_MATCHES: Match[] = [
  {
    id: "m1",
    homeTeam: "ريال مدريد",
    awayTeam: "برشلونة",
    league: "الدوري الإسباني - الكلاسيكو",
    date: "اليوم",
    time: "مباشر الآن",
    score: "2 - 2",
    homeScore: 2,
    awayScore: 2,
    status: "live",
    minute: 74,
    stadium: "سانتياغو برنابيو",
    referee: "خيسوس جيل مانزانو",
    attendance: 81044,
    stats: {
      homePossession: 53,
      awayPossession: 47,
      homeShots: 15,
      awayShots: 12,
      homeShotsOnTarget: 6,
      awayShotsOnTarget: 5,
      homeCorners: 6,
      awayCorners: 4,
      homeFouls: 9,
      awayFouls: 11,
      homeYellowCards: 2,
      awayYellowCards: 3,
      homeRedCards: 0,
      awayRedCards: 0
    },
    events: [
      { minute: 18, type: "goal", team: "away", player: "روبرت ليفاندوفسكي", detail: "رأسية متقنة مخادعة إثر عرقلة هجومية فاشلة من الدفاع" },
      { minute: 31, type: "goal", team: "home", player: "كيليان مبابي", detail: "انفراد تام بالمرمى وتسديدة صاروخية سكنت الشباك" },
      { minute: 55, type: "card", team: "home", player: "أوريلين تشواميني", detail: "بطاقة صفراء لتدخل تكتيكي لمنع مرتدة" },
      { minute: 62, type: "goal", team: "away", player: "رافينيا", detail: "متابعة ذكية لتمريرة سريعة من اليمين" },
      { minute: 71, type: "goal", team: "home", player: "جود بيلينجهام", detail: "تسديدة رائعة من حافة منطقة الجزاء بعد اختراق من الوسط" }
    ],
    preMatchAnalysis: "كلاسيكو الأرض يأتي وسط تقارب نقطي كبير. يعتمد ريال مدريد على التحولات السريعة المباشرة، في حين يطمح برشلونة للسيطرة والضغط الخانق في نصف ملعب الميرنغي.",
    aiCommentary: "تشتعل الإثارة في البرنابيو الآن! مباراة مفتوحة هجومياً بامتياز مع مرونة عالية في خطوط الضغط والتحولات الهجومية الخاطفة لكلا الفريقين."
  },
  {
    id: "m2",
    homeTeam: "الهلال",
    awayTeam: "النصر",
    league: "دوري روشن السعودي - ديربي الرياض",
    date: "أمس",
    time: "انتهت",
    score: "3 - 1",
    homeScore: 3,
    awayScore: 1,
    status: "finished",
    stadium: "ملعب المملكة أرينا",
    referee: "ويلمار رولدان",
    attendance: 26000,
    stats: {
      homePossession: 58,
      awayPossession: 42,
      homeShots: 18,
      awayShots: 10,
      homeShotsOnTarget: 9,
      awayShotsOnTarget: 3,
      homeCorners: 7,
      awayCorners: 2,
      homeFouls: 12,
      awayFouls: 15,
      homeYellowCards: 2,
      awayYellowCards: 4,
      homeRedCards: 0,
      awayRedCards: 1
    },
    events: [
      { minute: 8, type: "goal", team: "home", player: "الكسندر ميتروفيتش", detail: "ضربة رأس في الزاوية الضيقة للحارس" },
      { minute: 39, type: "card", team: "away", player: "إيميريك لابورت", detail: "بطاقة صفراء بسبب الاعتراض المتكرر" },
      { minute: 52, type: "goal", team: "home", player: "سيرجي ميلينكوفيتش سافيتش", detail: "تسديدة ساقطة من فوق الحارس مستفيداً من كسر مصيدة التسلل" },
      { minute: 77, type: "goal", team: "away", player: "كريستيانو رونالدو", detail: "ركلة جزاء نفذها بقوة على يمين ياسين بونو" },
      { minute: 88, type: "card", team: "away", player: "علي لاجامي", detail: "بطاقة حمراء مباشرة بعد مراجعة تقنية الفيديو للخشونة" },
      { minute: 90.3, type: "goal", team: "home", player: "سالم الدوسري", detail: "مهارة فردية ومراوغة رائعة تلتها تسديدة مقوّسة زاحفة" }
    ],
    preMatchAnalysis: "ديربي العاصمة في المملكة أرينا. يطمح الهلال للحفاظ على سلسلة اللاهزيمة، بينما يسلح النصر قوته الهجومية الضاربة لاستعادة النقاط وتضييق الفارق في قمة روشن.",
    aiCommentary: "نهاية مواجهة ديربي مجنونة في دوري روشن! الهلال يثبت سيطرته التكتيكية المطلقة مستفيداً من هفوات الضيوف الدفاعية والنقص العددي في الدقائق الأخيرة من المباراة."
  },
  {
    id: "m3",
    homeTeam: "الأهلي",
    awayTeam: "الزمالك",
    league: "الدوري المصري الممتاز - ديربي القاهرة",
    date: "أمس",
    time: "انتهت",
    score: "2 - 0",
    homeScore: 2,
    awayScore: 0,
    status: "finished",
    stadium: "ستاد القاهرة الدولي",
    referee: "أمين عمر",
    attendance: 50000,
    stats: {
      homePossession: 51,
      awayPossession: 49,
      homeShots: 11,
      awayShots: 8,
      homeShotsOnTarget: 5,
      awayShotsOnTarget: 2,
      homeCorners: 4,
      awayCorners: 5,
      homeFouls: 14,
      awayFouls: 17,
      homeYellowCards: 3,
      awayYellowCards: 4,
      homeRedCards: 0,
      awayRedCards: 0
    },
    events: [
      { minute: 34, type: "goal", team: "home", player: "وسام أبو علي", detail: "متابعة لتمريرة عرضية متقنة أفرغت الدفاع الأبيض" },
      { minute: 83, type: "goal", team: "home", player: "إمام عاشور", detail: "تسديدة قوية من خارج منطقة الجزاء سكنت أقصى الزاوية اليسرى" }
    ],
    preMatchAnalysis: "مواجهة الحصاد والقمة كالعادة. المنظومة الدفاعية للأهلي تواجه الحلول الهجومية المبتكرة للزمالك.",
    aiCommentary: "لقب القمة يعود للقلعة الحمراء بفضل التنظيم الدفاعي المحكم والاستغلال الأمثل للهجمات המرتدة الفعالة خلال الشوط الثاني."
  },
  {
    id: "m4",
    homeTeam: "مانشستر سيتي",
    awayTeam: "ليفربول",
    league: "الدوري الإنجليزي الممتاز",
    date: "غداً",
    time: "20:30",
    score: "0 - 0",
    homeScore: 0,
    awayScore: 0,
    status: "scheduled",
    stadium: "ملعب الاتحاد",
    referee: "أنتوني تايلور",
    attendance: 53400,
    stats: {
      homePossession: 50,
      awayPossession: 50,
      homeShots: 0,
      awayShots: 0,
      homeShotsOnTarget: 0,
      awayShotsOnTarget: 0,
      homeCorners: 0,
      awayCorners: 0,
      homeFouls: 0,
      awayFouls: 0,
      homeYellowCards: 0,
      awayYellowCards: 0,
      homeRedCards: 0,
      awayRedCards: 0
    },
    events: [],
    preMatchAnalysis: "الذكاء الاصطناعي يتوقع مواجهة استثنائية بنسبة احتمالية فوز مانشستر سيتي 42% تعادل 28% وفوز ليفربول 30%. يكمن المفتاح في السيرة الهجومية لصلاح وإيرلينج هالاند وتنشيط الأطراف البديلة."
  },
  {
    id: "m5",
    homeTeam: "بايرن ميونخ",
    awayTeam: "بوروسيا دورتموند",
    league: "الدوري الألماني - دير كلاسيكر",
    date: "بعد غد",
    time: "19:30",
    score: "0 - 0",
    homeScore: 0,
    awayScore: 0,
    status: "scheduled",
    stadium: "أليانز أرينا",
    referee: "فيليكس زواير",
    attendance: 75000,
    stats: {
      homePossession: 50,
      awayPossession: 50,
      homeShots: 0,
      awayShots: 0,
      homeShotsOnTarget: 0,
      awayShotsOnTarget: 0,
      homeCorners: 0,
      awayCorners: 0,
      homeFouls: 0,
      awayFouls: 0,
      homeYellowCards: 0,
      awayYellowCards: 0,
      homeRedCards: 0,
      awayRedCards: 0
    },
    events: [],
    preMatchAnalysis: "البايرن يطمح لتأكيد هيمنته في القلعة البافارية، توقعاتنا تشير إلى رغبة دورتموند في المبادرة للتسجيل من العمق."
  }
];
